--
-- PostgreSQL database dump
--

\restrict V6DqicP2WGYA8AQA73nEYS1RJLbwgjJZd8oHUItXdD9VtTNCRh2aXFS42eK4uKs

-- Dumped from database version 18.3
-- Dumped by pg_dump version 18.3

-- Started on 2026-05-08 13:10:23

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16563)
-- Name: Answers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Answers" (
    "Id" integer NOT NULL,
    "QuestionId" integer NOT NULL,
    "Text" text NOT NULL,
    "IsCorrect" boolean NOT NULL
);


ALTER TABLE public."Answers" OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 16562)
-- Name: Answers_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Answers" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Answers_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16575)
-- Name: Questions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Questions" (
    "Id" integer NOT NULL,
    "QuizId" integer NOT NULL,
    "Text" text NOT NULL,
    "Type" text NOT NULL,
    "Weight" integer NOT NULL,
    "MediaUrl" text
);


ALTER TABLE public."Questions" OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 16574)
-- Name: Questions_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Questions" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Questions_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16588)
-- Name: Quizzes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Quizzes" (
    "Id" integer NOT NULL,
    "Title" text NOT NULL,
    "Description" text NOT NULL,
    "Category" text NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "DurationMinutes" integer NOT NULL,
    "Attempts" integer NOT NULL,
    "PassingScore" integer NOT NULL,
    "ShowCorrectAnswers" boolean NOT NULL,
    "TeacherId" integer NOT NULL
);


ALTER TABLE public."Quizzes" OWNER TO postgres;

--
-- TOC entry 224 (class 1259 OID 16587)
-- Name: Quizzes_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Quizzes" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Quizzes_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 16607)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "Username" text NOT NULL,
    "Email" text NOT NULL,
    "PasswordHash" text NOT NULL,
    "Role" text NOT NULL,
    "IsBlocked" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 16606)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16555)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 4987 (class 0 OID 16563)
-- Dependencies: 221
-- Data for Name: Answers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Answers" ("Id", "QuestionId", "Text", "IsCorrect") FROM stdin;
\.


--
-- TOC entry 4989 (class 0 OID 16575)
-- Dependencies: 223
-- Data for Name: Questions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Questions" ("Id", "QuizId", "Text", "Type", "Weight", "MediaUrl") FROM stdin;
\.


--
-- TOC entry 4991 (class 0 OID 16588)
-- Dependencies: 225
-- Data for Name: Quizzes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Quizzes" ("Id", "Title", "Description", "Category", "StartDate", "EndDate", "DurationMinutes", "Attempts", "PassingScore", "ShowCorrectAnswers", "TeacherId") FROM stdin;
\.


--
-- TOC entry 4993 (class 0 OID 16607)
-- Dependencies: 227
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "Username", "Email", "PasswordHash", "Role", "IsBlocked", "CreatedAt") FROM stdin;
\.


--
-- TOC entry 4985 (class 0 OID 16555)
-- Dependencies: 219
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20260507180018_InitialCreate	10.0.0
\.


--
-- TOC entry 4999 (class 0 OID 0)
-- Dependencies: 220
-- Name: Answers_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Answers_Id_seq"', 1, false);


--
-- TOC entry 5000 (class 0 OID 0)
-- Dependencies: 222
-- Name: Questions_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Questions_Id_seq"', 1, false);


--
-- TOC entry 5001 (class 0 OID 0)
-- Dependencies: 224
-- Name: Quizzes_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Quizzes_Id_seq"', 1, false);


--
-- TOC entry 5002 (class 0 OID 0)
-- Dependencies: 226
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, false);


--
-- TOC entry 4831 (class 2606 OID 16573)
-- Name: Answers PK_Answers; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Answers"
    ADD CONSTRAINT "PK_Answers" PRIMARY KEY ("Id");


--
-- TOC entry 4833 (class 2606 OID 16586)
-- Name: Questions PK_Questions; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Questions"
    ADD CONSTRAINT "PK_Questions" PRIMARY KEY ("Id");


--
-- TOC entry 4835 (class 2606 OID 16605)
-- Name: Quizzes PK_Quizzes; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Quizzes"
    ADD CONSTRAINT "PK_Quizzes" PRIMARY KEY ("Id");


--
-- TOC entry 4837 (class 2606 OID 16620)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 4829 (class 2606 OID 16561)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2026-05-08 13:10:24

--
-- PostgreSQL database dump complete
--

\unrestrict V6DqicP2WGYA8AQA73nEYS1RJLbwgjJZd8oHUItXdD9VtTNCRh2aXFS42eK4uKs

